# An example of ClusterConfig with a normal nodegroup and a Fargate profile.
# 
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fargate-cluster
  region: ap-northeast-1

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
  - name: fp-dev
    selectors:
      - namespace: app-dev
        labels:
          fargate: 'yes'
